[package]
name = "core-utils"
version = "0.1.0"
description = "A bunch of core-utils re-written in rust."
edition = "2024"
repository = "https://github.com/evictedcucumber/core-utils"

[[bin]]
name = "rls"
path = "src/bin/ls/main.rs"
description = "A rust rewrite of the `ls` tool."

[dependencies]
